### ISSUE TITLE
Crash on startup with Frame API

### ISSUE THREAD

**Issue by SplendidAlakey** [Pepe20129/splashesplus#1]
**MC** 1.19.2
**QSL** 4.0.0 beta 9
**Splashes+** 0.1.2
**[Frame API](https://www.curseforge.com/minecraft/mc-mods/frame-api)** 0.26.1

Logs: https://gist.github.com/Footage2-Amply-Pounce/f754d3784d7fc76a374c9d988da74c60

**Comment by Pepe20129** [comment]
Fixed in 0.1.3
